### ISSUE TITLE
Experiments cmdline parameters

### ISSUE THREAD

**Issue by goastler** [uea-machine-learning/tsml#138] opened 2019-08-14 23:14 UTC
Idea for dealing with the current ClassifierLists issue of handling parameters. Defining a name with the parameter, e.g. "RotF<100/200/500>" becomes clunky with a large number of parameter options.

Currently there's 2 use cases:
1. I have some predetermined hyper-parameters that I want to set, e.g. numTrees, and I want to pass this via cmdline.
2. I have some predetermined *dependent* parameters that I want to set via cmdline, say build time limit, e.g. 1m, 2m, 5m, 10m, 30m, 1h. Each of these is dependent on the previous and it is redundant to have 6 different cluster jobs, one for each time limit, as work would be repeated. It would be better to run one job which contracts the classifier for 1m, records results, 2m, records results, etc...

Current thoughts on how this would work on the cmdline is:
1. pass the parameter key/values as a string separated by spaces, e.g. "-p param1 val1 param2 val2".
2. pass incremental parameter sets in the same way, but each increment is a separate cmdline option, e.g. "-ip trainContract 60 -ip trainContract 120 -ip trainContract 300".

Benefits:
- easy parameter passing for experiments, everything can be passed from the bash script which makes it easier to loop over parameters
- no need to define a new classifier id (e.g. RotF200) per parameter you're examining
- future proofing, every parameter for a classifier can be passed through this interface so there's no need to add more and more jcommander options as parameters grow

I have a hacky version on the ee branch currently: https://github.com/uea-machine-learning/tsml/blob/a0278c0f11ae2fa5e8812bbef229debd69cdfdac/src/main/java/experiments/Experiments.java#L102

**Comment by TonyBagnall** [comment] 2019-08-15 10:46
in terms of input, this is one for james. In terms of structure, we are using setOptions to set the parameters. If the parameter may be dependent on the data, we use a lambda to set it. 
![image](https://user-images.githubusercontent.com/9594042/63090098-1a3dec00-bf52-11e9-87d7-157cfa7bf94b.png)

for the incremental timing model, I'm not sure how that would work with results, because you need them after each time step. An alternative would be to do single runs with check pointing, so run contract for 60 with checkpointing on at the end, then run contract for 120?

**Comment by TonyBagnall** [comment] 2019-08-15 11:30
so perhaps we just have a single optional argument for parameters that is passed to setOptions?

**Comment by James-Large** [comment] 2019-08-15 15:08
Agreed parameter passing is an important aspect to get done soonish for the clarity of classifier lists but also just generally useful functionality etc

**For parameters in general**, agreed you want a single cmdline parameter to set all classifier parameters. Would the usage in terms of quotes literally be 

`"-p param1 val1 param2 val2"` or could it be e.g. `-p="param1 val1 param2 val2"`

I'd prefer the latter, for consistency but also in part because you can then overload it with 

`-p=[path_to]/[file_containing_para_value_pairs_or_JSON_file]`

or maybe just separate those into -pl --paraList and -pf --paraFile.

Parameters/options for each classifier can then be stored in files alongside their results for future proofing/reproducability, maybe even as default functionality of experiments.java

**For incremental parameters**, this sounds like a fairly specific case for contracting, or you could argue it would be the same format if you wanted to pass parameter _spaces_ to tuned classifiers via command line.

In either case, I'd argue for keeping this within the -p cmdline arg, as e.g. a comma-separated list of values that a particular parameter (in this case, contract time) can take. How the classifier handles the list is up to the classifier in setOptions, same as any other parameter

e.g. a single, set contract time `-p="trainContract 60 anotherParameter anotherValue" `

e.g. incremental contract times  `-p="trainContract 60,120,180 anotherParameter anotherValue" `

In fact, generalising behaviour this way makes sense if you're wanting to checkpoint at each contract anyway

In setOptions


```
if option trainContract exists
    list<long> contracts = string.parse(trainContract value).split(",")
```


In buildClassifier loop


```
if contracting
    currentContract = contracts.first

while something
    //do an iteration of training work

    if contracting and filled currentContract
        pause timer
        checkpoint if wanted
        evaluate if wanted
        write whatever else wanted
        currentContract = contracts.next
        resume timer
```

**Comment by goastler** [comment] 2019-08-16 23:35
> in terms of input, this is one for james. In terms of structure, we are using setOptions to set the parameters. If the parameter may be dependent on the data, we use a lambda to set it.
> ![image](https://user-images.githubusercontent.com/9594042/63090098-1a3dec00-bf52-11e9-87d7-157cfa7bf94b.png)
> 
> for the incremental timing model, I'm not sure how that would work with results, because you need them after each time step. An alternative would be to do single runs with check pointing, so run contract for 60 with checkpointing on at the end, then run contract for 120?

Yeah I'm doing the lambda structure to set EE's distance measure parameters and I quite like that structure! 

For the incremental timing I thought something along the lines of set contract, build classifier, test classifier, write results, set the next contract, repeat.... I appreciate you could checkpoint each of those contract times but I think that should be optional as it isn't required to run

**Comment by goastler** [comment] 2019-08-16 23:43
> Agreed parameter passing is an important aspect to get done soonish for the clarity of classifier lists but also just generally useful functionality etc
> 
> **For parameters in general**, agreed you want a single cmdline parameter to set all classifier parameters. Would the usage in terms of quotes literally be
> 
> `"-p param1 val1 param2 val2"` or could it be e.g. `-p="param1 val1 param2 val2"`

I'd prefer the latter too, it works much better with bash scripts and the jCommander syntax is cleaner.

> I'd prefer the latter, for consistency but also in part because you can then overload it with
> 
> `-p=[path_to]/[file_containing_para_value_pairs_or_JSON_file]`
> 
> or maybe just separate those into -pl --paraList and -pf --paraFile.

Yeah param settings in file is a good idea, though I think those could be read from file in bash and populated in (i.e. bash has redirects to read the contents of a file nice and easily compared to java which makes more sense in this context imo). Or have the -pf option, whichever (both is probs best) :)

> 
> Parameters/options for each classifier can then be stored in files alongside their results for future proofing/reproducability, maybe even as default functionality of experiments.java

Potentially yeah, it would be nice to couple that with a shift over to JSON

> **For incremental parameters**, this sounds like a fairly specific case for contracting, or you could argue it would be the same format if you wanted to pass parameter _spaces_ to tuned classifiers via command line.
> 
> In either case, I'd argue for keeping this within the -p cmdline arg, as e.g. a comma-separated list of values that a particular parameter (in this case, contract time) can take. How the classifier handles the list is up to the classifier in setOptions, same as any other parameter
> 
> e.g. a single, set contract time `-p="trainContract 60 anotherParameter anotherValue" `
> 
> e.g. incremental contract times `-p="trainContract 60,120,180 anotherParameter anotherValue" `
> 
> In fact, generalising behaviour this way makes sense if you're wanting to checkpoint at each contract anyway
> 
> In setOptions
> 
> ```
> if option trainContract exists
>     list<long> contracts = string.parse(trainContract value).split(",")
> ```
> 
> In buildClassifier loop
> 
> ```
> if contracting
>     currentContract = contracts.first
> 
> while something
>     //do an iteration of training work
> 
>     if contracting and filled currentContract
>         pause timer
>         checkpoint if wanted
>         evaluate if wanted
>         write whatever else wanted
>         currentContract = contracts.next
>         resume timer
> ```

Hmmm yeah that works in the case of contracting, but not in the case of tinkering with a param of a classifier. For instance, EE neighbourhood size is something which I've been tinkering with and it's incremental. I'd like to be able to run DTW_1NN with 10%, 50%, then 100% of neighbours, if you see what I mean

**Comment by ABostrom** [comment] 2019-08-22 10:32
I think I need to review this for Shapelet Transform too. 

I like the idea of running a transform for 1minute, then extending that by another minute. 

I am concerned that we could be accused of post-hoc cheating though. Run a classifier/transformer for a bunch of different time lengths, and then pick the best one. We would assume more time makes it better but in practice this hasn't always been true. 

From an engineering point of view, if we're seeding our experiments this shouldn't make a difference though. The order in which you do stuff is deterministic. 

I think we should also think about the contracting API a little more. 

FitClassifier(Train)
FitClassifierForTime(Train, TimeLimit)


How do we propose we extend the current runtime. 

Let's say I've run a model/transformer for 1minute. 

Would you call FitClassifier again, or would you want some additional function to extend the fitting process?

**Comment by James-Large** [comment] 2019-08-22 11:10
Mentioned in a couple chats, posting here too

On incremental contracts, I think it would take a lot of algorithmic work/changes to make that general behaviour, and sort of goes back to discussions on contracting before

Suppose I contract the build for 1min, and then increment to 2min and continue build. Is the 1min+1min build the same as the 2min build? (There's arguments about reproducability of exact computational work based on the background system etc, let's ignore that since that's the case for anything to do with contracting).

For e.g. ee and st they probably are the same afaik

For e.g. rise (iirc @MJFlynn), parameters of the build process aside from #iterations or %ofspacecovered etc are edited in order to meet the contract (interval sizes considered etc). The work done to meet the first 1min contract would be algorithmically different to the work done in the first minute of a 2min contract

#iterations or %ofspacecovered are I guess factors that monotically increase/decrease over time, where the contract simply defines _how far through the space you get, not how you get through it_

In terms of what this means for actually coding it, I don't know. An extra interface, `IncrementallyContractable extends Contractable, Checkpointable` ? It feels quite classifier-bespoke to me, unsure of how much effort should be spent making it generalised behaviour

**Comment by James-Large** [comment] 2019-08-22 11:23
And to some extent that's just formalising the discussion we had previously of potentially simplifying/homogenising the ways in which each classifier does contracting

**Comment by TonyBagnall** [comment] 2019-08-22 19:09
my opinion is that we should keep contracting internalised for now and the restart should be handled with checkpointing. Obvs, george can diverge, but I want the standard use case working and properly tested first

**Comment by TonyBagnall** [comment] 2019-10-07 19:48
bumping this, was any conclusion reached? If not we can defer and I'll leave it open. If yes (and I am happy to defer) could someone do it?

**Comment by TonyBagnall** [comment] 2020-02-14 17:31
I'm closing this as there has been no progress, can reopen if anyone wants to do it

**Closed by TonyBagnall** 2020-02-14 17:31 UTC
